### PR TITLE
Libretro drc fixes2

### PR DESCRIPTION
**Pull request by notaz**

### CODE REVIEW

**Comment by notaz** [comment]
Not sure if there is much left to come but commit access might still be helpful.

**Comment by twinaphex** [comment]
Thanks for this.

**Comment by twinaphex** [comment]
Hi @notaz , 

sorry for the late response but I gave you an invite granting you write access. Sorry for taking so long to get back to you. Hope my apology is sufficient.

**Comment by notaz** [comment]
No worries, I myself am not that responsive either, those dynarec stability issues were pending for years.

**Pull request merged**
