### PR TITLE
updated gaussian audio interpolation

### PR DESCRIPTION
**Pull request by Sakitoshi**
the current gaussian filter is pretty old and inaccurate for no good reason so I changed it with the one used in the updated peops sound plugin 1.10b which is much better.

### CODE REVIEW

**Comment by Darknior** [comment]
Thanks a lot, there are so few updates for this great emulator :)

**Comment by hhromic** [comment]
Thanks indeed! Not so long ago some users of RetroPie were having issues with sound interpolation and the Spyro 2/3 games. I also found these issues in my own setup.
If/when this PR gets merged maybe would be a good test case for your implementation!

Ref: https://retropie.org.uk/forum/topic/20344/spyro-2-and-3-audio-issue-with-psx-emulator

**Comment by Sakitoshi** [comment]
@hhromic 
my test was against akumajou dracula x gekka no yasokyoku (japanese castlevania symphony of the night) konami logo intro. it sounds horrible with the current gaussian interpolation.

here is how it sounds:
https://drive.google.com/file/d/1bxMO6x-nvHw0RGlb2Q-ifvClZcj35NWA/view?usp=sharing

it only happens there in that game however, so it wasn't a big issue. but I figured it would give real problems in other titles.

**Comment by hhromic** [comment]
@Sakitoshi 
the crackling problems identified for the Spyro games were using the **simple** audio interpolation, and they go away when disabling interpolation completely.
I'm hoping that with your PR, one can set the interpolation to **gaussian** instead of simple and get even better sound quality than with simple and no crackling.
However I don't know if the gaussian interpolation is too stressful for a Raspberry Pi 2/3. What platform did you test your game?

**Comment by Sakitoshi** [comment]
@hhromic 
**simple** and **cubic** don't give the problem mentioned above, only **gaussian**.
I tested on pc and raspi 3. raspi 3 still runs at full speed without overclocking. gaussian interpolation isn't particularly more taxing than the other methods afaik, so it shouldn't impact performance unless you have a literal potato.

**Comment by hhromic** [comment]
@Sakitoshi 
I just tested the core without your PR on a Raspberry Pi 3B+ and indeed the old gaussian interpolation doesn't show any particular slowdowns.   With that interpolation also I don't hear the crackles, but sounds better than **simple**, so looking forward to your patch!  Thanks!

**Pull request merged**
