### PR TITLE
iOS Compilation Updates

### PR DESCRIPTION
**Pull request by hevey**
now tested building for ios, ios9 and ios-arm64 all compiling again.

Have ran arm64 version, however unable to test others.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi @fetzerch, you want to test this before we merge this?

**Comment by fetzerch** [comment]
Sure, will give it a try later this evening.

**Comment by fetzerch** [comment]
Seems to work find on linux. Thanks!

**Comment by hevey** [comment]
@twinaphex is there anything I need to do to get this merged?

**Pull request merged**
