### PR TITLE
Sync upstream commits lost during recent PR squash

### PR DESCRIPTION
**Pull request by hhromic**
Recently, PR #260 was proposed and merged to sync up recent changes from upstream.

That PR intended to brough 4 commits from upstream, however it was merged via squashing.
The result is that despite the changes still being applied here, the repository is not tracking the original upstream commits properly (we are still 4 commits behind):

image

This PR brings down these 4 commits from upstream and thus re-syncs the repo. Because the changes were already applied, there are no file changes in this PR, just commit re-syncing.

For the future, I would recommended to not squash-merge upstream-syncing PRs.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I squashed it because it had like 3 or 4 merge commits wrapped around the same number of actual commits, but you're right that it's better to have the separate upstream commits.

**Comment by hhromic** [comment]
Yes I agree these "merge" commits are far from pretty in GitHub. This PR even introduced a new one :(
However squashing also defeats tracking upstream commits unfortunately. I think just keeping an eye on not squashing PRs with commits from upstream is enough to keep the repo tidy.
Thanks for merging anyway.

**Comment by retro-wertz** [comment]
well sorry for the mess. my whole idea is to send PR to upstream then merge from there since this is a core-related update (or at least my way of sharing back to core.)

**Comment by hizzlekizzle** [comment]
nah, you did the right thing. It is better to run things through upstream whenever possible.

I was just trying to keep things tidy but hhromic was right that it's better to have a few extraneous merge commits than to have vague, monolithic "sync to upstream" commits that are hard to bisect.

**Comment by hhromic** [comment]
@retro-wertz  yes you did right, in fact the PR I sent is exactly the same as yours!

Definitively you have the right attitude: contribute upstream, then bring down here and keep the core and upstream as much as in sync as possible.

This PR was mostly to aid on tracking your syncing, as GitHub can only track the alignment of the repositories correctly if the original commits are preserved. It was a little mistake to squash-merge them but we are all humans and luckily we can spot these mistakes timely.
Btw thanks for taking care of the core and keeping it alive. Appreciated!

**Pull request merged**
