### PR TITLE
libretro: Split update_controller_port_device()

### PR DESCRIPTION
**Pull request by Kekun**
Split update_controller_port_device() into
update_controller_port_variable() updating the controllers from the
variables, update_controller_port_device() updating the controllers from
retro_set_controller_port_device() and controller_port_variable()
sharing getting the controller variable between the two.

Avoid setting to PSE_PAD_TYPE_NONE controllers whose variable is set to
'default' when updating them.

### CODE REVIEW

**Comment by Kekun** [comment]
Hopefully, this one should really be good... sorry for the dirty commits.

**Comment by joolswills** [comment]
Just FYI, your previous PR broke compilation for the RPI

```
frontend/libretro.c: In function ‘update_multitap’:
frontend/libretro.c:471:3: warning: statement with no effect [-Wunused-value]
   auto_case == 1;
   ^
frontend/libretro.c:477:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int port = 2; port < PORTS_NUMBER; port++)
   ^
frontend/libretro.c:477:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
frontend/libretro.c:494:3: warning: statement with no effect [-Wunused-value]
   auto_case == 1;
   ^
frontend/libretro.c:500:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int port = 4; port < PORTS_NUMBER; port++)
   ^
frontend/libretro.c: In function ‘update_variables’:
frontend/libretro.c:1206:4: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
    for (int i = 0; i < PORTS_NUMBER; i++)
    ^
```

`i` needs to be declared outside of the loop for c89 compatibility.

**Comment by Alcaro** [comment]
And those ==s look about ten kinds of wrong.

And the libretro specification guarantees that retro_set_environment is the first function called and that it's non-NULL, so those checks aren't needed (though they are mostly harmless).

**Comment by joolswills** [comment]
This PR fixes the `==` issue.

**Pull request merged**
