### PR TITLE
fixes link time errors on the RPi platform (tested with 3 and 4)

### PR DESCRIPTION
**Pull request by dmorilha**
...was testing this over the weekend and had to apply these fixes for it to work on the raspberry pi platform. Audio is still missing but that might be related with something else.

### CODE REVIEW

**Comment by jdgleaver** [comment]
While this may fix link time errors on the RPi, unfortunately it breaks compilation on most other platforms...  :)

What you've done here is remove the definitions of `rcnts` and `psxRegs`. Thus we have *declarations* (extern, in headers) but no definitions at all. This isn't valid C... I'm very surprised that any complier will accept that (and even if it does, it has to be undefined behaviour)

**Comment by dankcushions** [comment]
also, lr-pcsx_rearmed has been the default psx emulator for retropie for years. not aware of any build errors...

**Comment by dmorilha** [comment]
```
$ uname -a; gcc --version; git log -n 1 --oneline; make -f Makefile.libretro platform=rpi4;
Linux livingroom2 5.4.72-1-ARCH #1 SMP PREEMPT Mon Oct 19 15:33:47 UTC 2020 armv7l GNU/Linux
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

19b9695 (HEAD, origin/master, origin/HEAD, master, makepkg) Merge pull request #456 from justinweiss/3ds-spu-threading
cc -o pcsx_rearmed_libretro.so libpcsxcore/cdriso.o libpcsxcore/cdrom.o libpcsxcore/cheat.o libpcsxcore/debug.o libpcsxcore/decode_xa.o libpcsxcore/disr3000a.o libpcsxcore/mdec.o libpcsxcore/misc.o libpcsxcore/plugins.o libpcsxcore/ppf.o libpcsxcore/psxbios.o libpcsxcore/psxcommon.o libpcsxcore/psxcounters.o libpcsxcore/psxdma.o libpcsxcore/psxhle.o libpcsxcore/psxhw.o libpcsxcore/psxinterpreter.o libpcsxcore/psxmem.o libpcsxcore/r3000a.o libpcsxcore/sio.o libpcsxcore/socket.o libpcsxcore/spu.o libpcsxcore/gte.o libpcsxcore/gte_nf.o libpcsxcore/gte_divider.o deps/zlib/adler32.o deps/zlib/compress.o deps/zlib/crc32.o deps/zlib/deflate.o deps/zlib/gzclose.o deps/zlib/gzlib.o deps/zlib/gzread.o deps/zlib/gzwrite.o deps/zlib/inffast.o deps/zlib/inflate.o deps/zlib/inftrees.o deps/zlib/trees.o deps/zlib/uncompr.o deps/zlib/zutil.o libpcsxcore/gte_arm.o libpcsxcore/gte_neon.o libpcsxcore/new_dynarec/backends/psx/emu_if.o libpcsxcore/new_dynarec/new_dynarec.o libpcsxcore/new_dynarec/arm/linkage_arm.o libpcsxcore/new_dynarec/backends/psx/pcsxmem.o plugins/dfsound/dma.o plugins/dfsound/freeze.o plugins/dfsound/registers.o plugins/dfsound/spu.o plugins/dfsound/out.o plugins/dfsound/nullsnd.o plugins/dfsound/arm_utils.o plugins/gpulib/gpu.o plugins/gpulib/vout_pl.o plugins/gpu_neon/psx_gpu_if.o plugins/gpu_neon/psx_gpu/psx_gpu_arm_neon.o plugins/cdrcimg/cdrcimg.o deps/crypto/md5.o deps/crypto/sha1.o deps/flac-1.3.2/src/libFLAC/bitmath.o deps/flac-1.3.2/src/libFLAC/bitreader.o deps/flac-1.3.2/src/libFLAC/cpu.o deps/flac-1.3.2/src/libFLAC/crc.o deps/flac-1.3.2/src/libFLAC/fixed.o deps/flac-1.3.2/src/libFLAC/fixed_intrin_sse2.o deps/flac-1.3.2/src/libFLAC/fixed_intrin_ssse3.o deps/flac-1.3.2/src/libFLAC/float.o deps/flac-1.3.2/src/libFLAC/format.o deps/flac-1.3.2/src/libFLAC/lpc.o deps/flac-1.3.2/src/libFLAC/lpc_intrin_avx2.o deps/flac-1.3.2/src/libFLAC/lpc_intrin_sse2.o deps/flac-1.3.2/src/libFLAC/lpc_intrin_sse41.o deps/flac-1.3.2/src/libFLAC/lpc_intrin_sse.o deps/flac-1.3.2/src/libFLAC/md5.o deps/flac-1.3.2/src/libFLAC/memory.o deps/flac-1.3.2/src/libFLAC/metadata_iterators.o deps/flac-1.3.2/src/libFLAC/metadata_object.o deps/flac-1.3.2/src/libFLAC/stream_decoder.o deps/flac-1.3.2/src/libFLAC/window.o deps/lzma-16.04/C/Alloc.o deps/lzma-16.04/C/Bra86.o deps/lzma-16.04/C/Bra.o deps/lzma-16.04/C/BraIA64.o deps/lzma-16.04/C/CpuArch.o deps/lzma-16.04/C/Delta.o deps/lzma-16.04/C/LzFind.o deps/lzma-16.04/C/Lzma86Dec.o deps/lzma-16.04/C/Lzma86Enc.o deps/lzma-16.04/C/LzmaDec.o deps/lzma-16.04/C/LzmaEnc.o deps/lzma-16.04/C/LzmaLib.o deps/lzma-16.04/C/Sort.o deps/libchdr/bitstream.o deps/libchdr/cdrom.o deps/libchdr/chd.o deps/libchdr/flac.o deps/libchdr/huffman.o plugins/dfinput/main.o plugins/dfinput/pad.o plugins/dfinput/guncon.o frontend/cspace.o frontend/cspace_neon.o frontend/libretro.o frontend/main.o frontend/plugin.o -shared -Wl,--no-undefined -lm -lpthread -lm -ldl  
/usr/bin/ld: libpcsxcore/new_dynarec/arm/linkage_arm.o:(.bss+0x5c): multiple definition of `psxRegs'; libpcsxcore/r3000a.o:(.bss+0x0): first defined here
/usr/bin/ld: libpcsxcore/new_dynarec/arm/linkage_arm.o:(.bss+0x374): multiple definition of `rcnts'; libpcsxcore/psxcounters.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:385: pcsx_rearmed_libretro.so] Error 1
```

Am I doing something wrong?

**Comment by negativeExponent** [comment]
'multiple definition' issues for some platform was fixed with this:
https://github.com/libretro/pcsx_rearmed/commit/ddd39f209f4ce6f03ed3198d7d58c2e36565baa9

similar method might work in your case

**Comment by dmorilha** [comment]
great idea, I'll try and resubmit the PR

**Comment by negativeExponent** [comment]
@dmorilha : can you try editing libpcsxcore/new_dynarec/arm/linkage_arm.S
make the following changes:

diff --git a/libpcsxcore/new_dynarec/arm/linkage_arm.S b/libpcsxcore/new_dynarec/arm/linkage_arm.S
index 269eb99..fabf93c 100644
--- a/libpcsxcore/new_dynarec/arm/linkage_arm.S
+++ b/libpcsxcore/new_dynarec/arm/linkage_arm.S
@@ -61,7 +61,7 @@ DRC_VAR(pending_exception, 4)
 DRC_VAR(stop, 4)
 DRC_VAR(invc_ptr, 4)
 DRC_VAR(address, 4)
-DRC_VAR(psxRegs, LO_psxRegs_end - LO_psxRegs)
+/* DRC_VAR(psxRegs, LO_psxRegs_end - LO_psxRegs) */
 
 /* psxRegs */
 DRC_VAR(reg, 128)
@@ -76,7 +76,7 @@ DRC_VAR(pcaddr, 4)
 @DRC_VAR(interrupt, 4)
 @DRC_VAR(intCycle, 256)
 
-DRC_VAR(rcnts, 7*4*4)
+/* DRC_VAR(rcnts, 7*4*4) */
 DRC_VAR(mem_rtab, 4)
 DRC_VAR(mem_wtab, 4)
 DRC_VAR(psxH_ptr, 4)

**Pull request merged**
