### PR TITLE
lightrec: Update prototypes of memory write callbacks

### PR DESCRIPTION
**Pull request by pcercuei**
As requested.

### CODE REVIEW

**Comment by notaz** [comment]
Thanks, but strangely that write to `0x1f8010f0` doesn't reach `psxHwWrite16`. Maybe you have some optimization that prevents this?

**Comment by pcercuei** [comment]
> Thanks, but strangely that write to `0x1f8010f0` doesn't reach `psxHwWrite16`. Maybe you have some optimization that prevents this?

See the `lightrec_can_hw_direct` function - it probably needs to be whitelisted.

**Comment by notaz** [comment]
I assume that's only used for addresses known ahead of time?

**Comment by pcercuei** [comment]
> I assume that's only used for addresses known ahead of time?

Yes.

**Pull request merged**
