### PR TITLE
PSX clock and BIOS core options, memcard2 fix etc

### PR DESCRIPTION
**Pull request by retro-wertz**
**Use BIOS: "auto | HLE"**
- **auto** uses default behavior, which searches for specific bios files. if non is found, search for keyword "scph" on system dir for a psx bios file. If still nothing is found defaults to using HLE.
- **HLE** forces to use hle (built-in) bios (causes compatibility problems most commonly with memory cards)

**PSX cpu clock (dynarec): range: 30 - 100**
- Over/under-clock the PSX, default is 57 (10000 / 57 = 175)
- lower value = less work for the emu, may be faster;
- enabled and working only with **dynarec** mode, menu does not show on non-dynarec builds

reference post: https://github.com/libretro/pcsx_rearmed/issues/237

**5bf5626 Fix memcard2 still detected by games when its supposed to be disabled**
- reference https://github.com/libretro/pcsx_rearmed/issues/207
- when core option **Enable second memory card** is set to **disabled**, games still see that the memory card is still inserted or as uninitialize. Games like Tenka wants that memcard2 is removed and so fails to run game because of this behavior.
- Fixes done to HLE and when using real bios.

bc1fc5f  Use actual labels for input types
- using "defaults" is a bit confusing especially on multiplayer games, since defaults is standard controller on input 1/2 but defaults is none for inputs 3-8. using the actual labels should be limit this confusion and its clear what type on controller is used.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
So, for the pad types, the behavior for someone with no changes is still the same, right? That is, we're not going to be breaking everyone's input?

**Comment by retro-wertz** [comment]
since there is no "defaults" value anymore, in_type[n], i guess  will not be updated and will take whatever is set as default during emu_core_init(), which is only input 1 and 2 is assigned to PSE_PAD_TYPE_STANDARD.others are set to none or no input.

of course, manually updating in core options is still recommended, this should update retroarchs config as well.

**Comment by Loquo** [comment]
Hi! Thanks a lot for take my issue (reference #207) for fixing it.

I'm not an expert, then I have to ask: Is this fix already implanted in a update for pcsx_rearmed? Or we have to wait until a new updating package will be ready?

Thanks again!

**Comment by AnotherLife** [comment]
@Loquo When you load the core it tells you the commit it is based on at the bottom

Something like pcsx-rearmed r22 d917655
Then you can go to the commit history and look for "d917655", for example this would be from 26 March. What does your core build say?

https://github.com/libretro/pcsx_rearmed/commits/master

**Comment by Loquo** [comment]
Updated lr-PCSX-rearmed, checked and it works!

Thanks a lot!

**Pull request merged**
