### PR TITLE
Unlock Lightrec to its full potential

### PR DESCRIPTION
**Pull request by pcercuei**
Boost performance by running the dynarec until the next scheduled interrupt, instead of exiting after each compiled block.

### CODE REVIEW

**Comment by MarioKartFan** [comment]
@pcercuei Hi!  Would you expect this to impact performance on lower end devices as well (e.g., ARM devices like N3DS)?  Thanks!

**Comment by pcercuei** [comment]
@MarioKartFan yes, drastically. However by default ARM devices use Ari64's dynarec and not Lightrec.

**Comment by MarioKartFan** [comment]
@pcercuei Thank! I love learning from devs.  Very cool. Would similar changes also improve the speed of ari64‘s dynarec or is it already doing something similar?

**Comment by pcercuei** [comment]
@MarioKartFan Ari64's dynarec does that already, yes.

**Pull request merged**
