### PR TITLE
unai: Add ARM-optimized lighting / blending functions

### PR DESCRIPTION
**Pull request by justinweiss**
Looking at the generated ASM on 3ds, I thought I could squeeze out some extra performance by moving the inner lighting and blending functions to handwritten A32 assembly. This branch gives a medium improvement generally (3-5fps faster on the beach in Crash 1) and a large improvement when doing lots of blending (46-48fps before, 57-60fps after, behind the waterfall in Water Dragon Isle in Chrono Cross).

I still have some cleanup and documentation I want to do before this is ready to merge, but wanted to open this for comment.

Some other notes: 
- I used the ARM11 MPCore (3DS CPU) timings for pipelining. 
- I had a few stall cycles during lighting, so I used them to preserve the MSB for lighting and blending, which saved a store, load, and `orr` later on. ~3-6 cycles saved overall by doing that.
- I switched from u16 to uint_fast16_t, which is 32-bit on this platform. This saved a few useless `uxth` instructions for another few cycles. This shouldn't affect other platforms, but I don't know for sure. Could typedef if necessary.
- A lot of the speed improvement in blending comes from not using two instructions per `and`. For example, `& 0x8000` -- the compiler preferred to mask out bytes using `bic 0x7F00` and `bic 0x00FF`. Both slower and seemed less correct for what we're trying to do.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I think @m4xw or themaister may have some insight. Just based on your testing, though, it sounds great to me :)

**Comment by DragonautMk** [comment]
I hope these optimizations are painless and gradually we can gain more and more from the n3ds. A boost of another 10 fps would allow many more titles to be considered playable at a good level.
In all this I would like to be able to play Policenauts on my N3ds.

**Comment by dankcushions** [comment]
very cool! just tried on Raspberry Pi 4 (ARM v8 in 32-bit mode), and it worked great. Pi 4 was plenty fast enough already so not much of a test, but at least no regressions that I could see.

**Comment by retrowertz** [comment]
rpi4 does not use unai by default

**Comment by justinweiss** [comment]
@dankcushions I'd be fine with bringing this upstream, I don't think there's a reason not to. 

Does the Pi 4 use unai? I would still expect gpu_neon to be faster where neon is supported.

**Comment by hizzlekizzle** [comment]
Yeah, the NEON renderer needs 32-bit syntax currently. Updating it to 64-bit NEON syntax shouldn't be too hard, but no one has done the dirty work yet.

**Comment by dankcushions** [comment]
sorry, didn't read this was for unai! yeah, all pis use the neon renderer.

**Comment by twinaphex** [comment]
I'm not an expert on ARM assembly to say the least, but I'm willing to merge this PR if you see no immediate obvious problems here.

It could bring immediate benefits for 3DS and it's better than letting the PR stay for an entire month like this, if any additional issues do pop up they can be resolved later.

**Comment by justinweiss** [comment]
Cool. With everything going on I forgot this was still sitting around.

I did the indentation cleanup and added some comments for the assembly so it's easier to understand for the next person to look at it. I've been running it myself for a while now.

**Comment by m4xw** [comment]
Oh I just saw this PR, Will take a look!

**Comment by twinaphex** [comment]
OK, we'll let @m4xw look at this. Let me know when this is fit for merge and we'll go ahead and do it.

**Pull request merged**
