### PR TITLE
Update lightrec 20230224

### PR DESCRIPTION
**Pull request by pcercuei**
Update GNU Lightning and Lightrec to the latest versions.

### CODE REVIEW

**Comment by pcercuei** [comment]
Updated Lightrec to https://github.com/pcercuei/lightrec/commit/fcf239e7e9d42fedb7a8de64057d6895acf3ceee

**Comment by notaz** [comment]
BTW while looking at the TOCA issue I've noticed that in `lightrec_mtc0` when reg=13 it uses garbage `oldstatus`. While this may look harmless, as this code as is would only sometimes return from lightrec needlessly (from what I understand), technicaly it's undefined behavior and the compiler is allowed to throw away the whole `&& (~oldstatus & 0x401)` comparison if it wants to.

gcc warns about it:
```
deps/lightrec/lightrec.c:514:57: warning: ‘oldstatus’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  514 |                 if (reg == 12 && !(~status & 0x401) && (~oldstatus & 0x401))
      |                                                         ^~~~~~~~~~
```
Yes there are tons of false-positive warnings in lightrec, like all the -Wparentheses stuff, but wouldn't it be better to have them fixed so that legit bug warnings like above don't get hidden in the lot?

**Comment by pcercuei** [comment]
GCC's warning about `oldstatus` is a false positive; the value is only read and written when reg=12, so this is not undefined behaviour. I think GCC issues the warning because it thinks that "reg" can alias. I don't get this warning on my system (debian testing, GCC 12).

I generally try to fix the warnings, although some remain (which should all be false positives). The CMake script passes `-Wno-parentheses` because it bothers me a bit to use parentheses when I think they aren't needed; although it did bite me in the past with `(a & b == c)` where the logical operator has precedence over the binary operator (which is beyond stupid if you ask me). So maybe I should re-enable the warning.

**Comment by notaz** [comment]
Hmm ok looking at it again you're right.

**Comment by notaz** [comment]
Looks like this broke Beat Mania (SLPM86126).

**Comment by pcercuei** [comment]
This game seems to work fine here, what's broken?

And while I have you... I have another PR but for your own repo (https://github.com/notaz/pcsx_rearmed/pull/292), should I send them to libretro/pcsx_rearmed in the future?

I also have a report that commits d0abba5d3a and 2c78ad6070 cause the core to go very slow on the WiiU (and reverting those two fix it). My guess is that it would be caused by `block_only` being true even after booting, but it doesn't seem to be the case, at least on my PC. Any thoughts?

**Comment by notaz** [comment]
> This game seems to work fine here, what's broken?

It only reproduced with useless reg save/load plus cache flush bug. Tracked it down myself, it was that `lightrec_dump_regs()` wrote some selected cp0 regs to psxRegs, did `psxException()`, but after all that `lightrec_plugin_sync_regs_to_pcsx()` would take outdated regs from lightrec again. Tried to clean this up in 6c62131f8b4a923e02bb8a9d8cd9f62a90fa20a7 (or mess it up even more, I'm not sure).

> I have another PR but for your own repo (https://github.com/notaz/pcsx_rearmed/pull/292)

Merged, it's a bit hard to keep track of everything sometimes.

**Pull request merged**
