### PR TITLE
enable memory card2

### PR DESCRIPTION
**Pull request by havenow**
open memory card2, so that it can be used!

### CODE REVIEW

**Comment by meepingsnesroms** [comment]
This is a good idea but is incomplete, the memory card also needs to be initialized.
Custom file saving is also required since retroarch only gives access to one save file through its api.

**Comment by twinaphex** [comment]
OK, so will we see any further progress on this front?

**Comment by FateForWindows** [comment]
I'm guessing this can be closed now that another memcard2 pull request has been merged?

**Comment by hizzlekizzle** [comment]
Closing this, as it seems it's already been solved elsewhere.

**Pull request closed without merging**
