### PR TITLE
Move pcsx init to retro load game

### PR DESCRIPTION
**Pull request by negativeExponent**
for review

@twinaphex @hunterk @hizzlekizzle

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi, I will have to ask @davidgfnet 's input on this one.

**Comment by davidgfnet** [comment]
Hey, jdgleaver explained why this is not a good idea in: https://github.com/libretro/gpsp/issues/132
Please do not merge this since this is .. a hack, and not a very good one :)
Can you please confirm that Retroarch is calling init()? This can be either a bad Retroarch version or a bad configuration (read jdgleaver's comment on why this happens).
Thanks!

**Comment by negativeExponent** [comment]
like what ive said, this only changes loading sequence, nothing here
changes how the core runs to begin with. Calling this a hack is absurd at
best without even testing if this breaks the core itself. How much
'performance' is lost by rearranging it this way like all the rest of the
cores are doing!!!! ' A BAD HACK' Yeah right. If you guys are really good
enough, they good luck tracking down tracking down and fixing issue with
the rest of the cores that are hardly maintained.. Im done, just too much
ego running around here.

@twinaphex please remove whatever rights i have on some cores here.

**Comment by davidgfnet** [comment]
Hey, I'm sorry that you felt that way, didn't mean to insult you or anything like that.
I'm not sure how this is an ego related issue, after all I'm asking for forgiveness here ^^'
So I was just pointing out that the init code is ok in retro_init, as it should. In some cases it can be indeed that retro_init is not called, but the right solution is fixing Retroarch so that it calls retro_init, instead of funnelling all the init code in load_game right? Perhaps the API is not the best API in the work (I could complain about it for hours :P) but in this case it sort of makes sense.
If you wanna chat about it, meet me in Discord!
Thanks for your contributions!

**Comment by twinaphex** [comment]
Replaced by this - https://github.com/libretro/pcsx_rearmed/pull/532

**Pull request closed without merging**
