### PR TITLE
Update GNU Lightning 2024-11-02

### PR DESCRIPTION
**Pull request by pcercuei**
Update GNU Lightning to the latest upstream version.

One notable change is that the upstream version now supports SH4 processors, which I use in my [downstream PCSX port for Dreamcast](https://github.com/pcercuei/bloom).

### CODE REVIEW

**Comment by pcercuei** [comment]
I switched to the official GIT repo as well, so it seems to have undone the "gnulib" submodule, how can I fix that?

**Comment by notaz** [comment]
Dunno, perhaps try git subrepo's `--ALL` option? Or maybe `git rm deps/lightning/gnulib` since it's not really needed (or is it?)? I wish libretro infra supported submodules already, this is an annoying difference from the master branch.

BTW I've meant to report this, but lightrec has problems with "Tomb Raider (USA) (Rev 2)" (http://redump.org/disc/12765/), when it loads it presents a menu from which the game doesn't start.

**Comment by notaz** [comment]
Any plans to solve this? Perhaps keep the unwanted submodule, which is lesser evil than the reduced CI coverage.

**Comment by pcercuei** [comment]
Yeah I was trying several things and could not get the CI to ignore the submodule. I'm on a motorcycle trip right now, will have a look when I get back.

**Comment by pcercuei** [comment]
> Any plans to solve this? Perhaps keep the unwanted submodule, which is lesser evil than the reduced CI coverage.

Ok, I tried a few things to no avail. I give up, so I added gnulib as a submodule to fix the CI now.

**Comment by pcercuei** [comment]
> BTW I've meant to report this, but lightrec has problems with "Tomb Raider (USA) (Rev 2)" (http://redump.org/disc/12765/), when it loads it presents a menu from which the game doesn't start.

That's still a problem? I can't find anything wrong with the game, it goes ingame just fine.

**Comment by notaz** [comment]
That's because I've added `LIGHTREC_HACK_INV_DMA_ONLY` for this in 0de3bab4d10281eecd4746e3700aafb6279f7c9e. This will break in case the games uses real self-modifying code somewhere though. But I suspect it doesn't.

**Pull request merged**
